### ISSUE TITLE
Des requetes SQL typés 🤔?

### ISSUE THREAD

**Issue by etienne-dldc** [ParisTypeScript/talks#10]
# Proposition de talk - Paris TypeScript

## Description du talk
* Titre : 
Des requetes SQL typés 🤔?

* Contenu (Décrivez brièvement le contenu de la présentation) :
Des requètes SQL type-safe c'est possible ! Dans ce talk on va parler de SQL (obviously), de comment écrire un Parser et inférence de type.

* Durée :
  - [ ] 5 minutes (Lightning talk)
  - [ ] 10 minutes
  - [ ] 20 minutes
  - [x] 30 minutes
  - [ ] Autres, précisez:
* Niveau :
  - [ ] Débutant
  - [x] Intermédiaire
  - [ ] Avancé

## A propos de vous
* Nom et prénom : Étienne DELADONCHAMPS
* Twitter : @Etienne_dot_js
* Entreprise :

**Comment by spontoreau** [comment]
Update avec le template, merci pour la proposition Etienne!
