### ISSUE TITLE
declaration file and library definition for UMD JS packages

### ISSUE THREAD

**Issue by Mouvedia** [ParisTypeScript/talks#13]
# Proposition de talk - Paris TypeScript

## Description du talk
* Titre : declaration file and library definition for UMD JS packages
* Contenu (Décrivez brièvement le contenu de la présentation) :
  - ce que j'ai fait et ce que ça apporte
  - différences entre TS et flow
  - demo ou/et QA (5 dernières minutes)
* Durée :
  - [ ] 5 minutes (Lightning talk)
  - [x] 10 minutes
  - [ ] 20 minutes
  - [ ] 30 minutes
  - [ ] Autres, précisez:
* Niveau :
  - [x] Débutant
  - [x] Intermédiaire
  - [x] Avancé

## A propos de vous
* Nom et prénom : N/A Gary
* Twitter : N/A
* Entreprise : N/A
* Trivia : J'ai gagné un livre lors d'un meetup TS.

**Comment by spontoreau** [comment]
Hello Marc,

Beaucoup d'eau à couler sous les ponts depuis ton proposal !

Je ne sais pas si ton sujet est toujours faisable + de 2 ans aprés, mais pour info on est de retour en physique donc n'hésites pas nous ping si jamais tu es tjrs chaud pour faire un talk au meetup.

Bonne journée,
Sylvain

**Comment by Mouvedia** [comment]
Hello @spontoreau,

> Beaucoup d'eau à couler sous les ponts depuis ton proposal !

Effectivement ça date.

> faisable + de 2 ans aprés

Sous une forme speed REX ou tutoriel, je pense ça peut passer.

> donc n'hésites pas nous ping si jamais tu es tjrs chaud pour faire un talk

Je passerai sur le channel slack lorsque j'aurai fait les slides.

**Comment by spontoreau** [comment]
Ok !

Pour info on va faire un meetup le 14 juin, si tu penses que c'est jouable fait moi signe ;)

**Comment by spontoreau** [comment]
Hello comment ça va ?

Je ne sais pas si tu es toujours intéressé pour faire cette présentation ?
