### ISSUE TITLE
[Talk Proposal] Fully-typed fullstack development using Blitz.js

### ISSUE THREAD

**Issue by Skn0tt** [ParisTypeScript/talks#17]
# Talk proposal - Paris TypeScript

## Talk description
* Title: Fully-typed fullstack development using Blitz.js
* Content: Although we're properly typing all our code using TypeScript, the type-soundness of our web projects is often lost in transit between frontend and backend. Blitz.js uses code generation to overcome that problem, allowing TypeScript to achieve end-to-end type coverage. The talk explains on why that's useful, how it works on a conceptual level and what we can learn from it.
* Duration:
  - [ ] 5 minutes (Lightning talk)
  - [ ] 10 minutes
  - [ ] 20 minutes
  - [x] 30 minutes
  - [ ] Other, please specify:
* Level:
  - [ ] Beginner
  - [x] Intermediate
  - [ ] Advanced

## About you
* Name: Simon Knott
* Twitter: @skn0tt
* Company: [EntE](https://ente.app), [HPI](https://hpi.de)

**Comment by spontoreau** [comment]
Hello @Skn0tt,

Thanks,

Finally we decided to just take 2 talks for our July online meetup. We don't know yet if we will continue to do online event at the beginning of September, so we will keep you in touch.

**Comment by Skn0tt** [comment]
Sounds good :)

**Comment by Skn0tt** [comment]
(accidental close 😅)

**Comment by spontoreau** [comment]
Hello Simon,

I know you proposal was made a long time ago when we were focus on streaming things, but this time is over and on our side we are now back on fully physical events at Paris.

So I'm closing this proposal even if it was a really great one !
