### ISSUE TITLE
Pot online post-meetup

### ISSUE THREAD

**Issue by moufmouf** [ParisTypeScript/talks#18]
Salut l'équipe de Paris TypeScript!

J'ouvre ce ticket, non pas pour vous proposer un talk, mais pour proposer un pot en ligne à la fin du meetup.

Une grande partie de l'intérêt d'un meetup ne tient pas dans les talks mais dans les rencontres que l'on peut faire.
Dans un meetup "online", cet intérêt est vite perdu, chacun étant chez soi sur Youtube. A la fin du meetup, impossible d'aller parler aux participants.

Durant le confinement, j'ai travaillé sur un projet permettant de recréer ce lien social. Et on vient de sortir quelque chose de pas trop mal (selon mes critères de dev).

Ca s'appelle WorkAdventure, et vous pouvez voir une démo ici: https://workadventu.re/
(ou une vidéo de présentation là: https://www.youtube.com/watch?v=h7UqvALMONs)

L'idée est simple: un univers virtuel à la façon des RPG 16-bits. On se déplace et dès qu'on s'approche de quelqu'un, on rentre en conversation avec lui. On peut former des groupes de discussion (jusqu'à 4 personnes). Pour un meetup, cela permet à chaque participant d'aller parler aux autres participants ou aux speakers facilement à la fin d'une session. Et aussi, c'est très fun!

Bonus de style, c'est développé en Typescript (front et back!) et le code est ici: https://github.com/thecodingmachine/workadventure/

Note: si vous cherchez encore des sujets pour la semaine prochaine, je peux également faire un talk sur le retour d'expérience de la création de WorkAdventure d'un point de vue Typescript.

**Comment by paulsouche** [comment]
Hello @moufmouf et merci de ta proposition.

Il est vrai que l'aspect social du meetup a un peu disparu depuis le confinement et c'est un sujet dont nous avons discuté entre organisateurs sans trouver de solution. Le plus gros problème que nous rencontrons est qu'il est très compliqué de modérer ce genre d'évènement. On parlera de ta proposition à notre prochain point mais pas sur que cela se fasse le 7 juillet....

Par ailleurs ce repository est dédié aux propositions de talks (n'hésite pas à proposer le tien même si le programme du 7 est bouclé, ce sera une prochaine fois). Du coup je vais close cette issue. Tu peux nous retrouver sur [slack](https://slackin.typescript-paris.now.sh/) et discuter directement avec nous.

Une bonne soirée
