### ISSUE TITLE
Gitmoji flow, a journey to commit like a hipster 🧔

### ISSUE THREAD

**Issue by spontoreau** [ParisTypeScript/talks#19]
# Talk proposal - Paris TypeScript

## Talk description
* Title:
Gitmoji flow, a journey to commit like a hipster 🧔

* Content (Briefly describe the content of the presentation):
"TMP"
"Fix some bugs"
"I changed that shit"

This may bring back bad memories and that's why commit message conventions are important. In your life as a developer you probably already applied them, but have you tried Emojis?

They are by nature expressive, very readable and they are useful in a lot of applications. I'll show you how you can use them to set up a developer workflow and commit like a hipster 🧔 !

* Duration:
  - [ ] 5 minutes (Lightning talk)
  - [ ] 10 minutes
  - [ ] 20 minutes
  - [ ] 30 minutes
  - [x] Other, please specify: 25min
* Level:
  - [x] Beginner
  - [ ] Intermediate
  - [ ] Advanced

## About you
* Name: Sylvain Pontoreau
* Twitter: @spontoreau

**Comment by dubzzz** [comment]
So cool! I want to see that (already using it on fast-check) but I often struggle to find the right one so your talk will be useful

**Comment by spontoreau** [comment]
^^

This is a topic I have in mind for a couple of week, it will be fun :P
