### ISSUE TITLE
Retour d'expériences sur différentes approches pour typer un client TypeScript d'une API externe

### ISSUE THREAD

**Issue by rdeneau** [ParisTypeScript/talks#2]
# Proposition de talk - Paris TypeScript

_Copie de la soumission effectuée le 05/03/2019 par Google Form_

## Description du talk

* Titre de la présentation :
  > Retour d'expériences sur différentes approches pour typer un client TypeScript d'une API externe
* Contenu _(Décrivez brièvement le contenu de la présentation)_ :
  > L'interfaçage d'un client TypeScript avec une API externe (REST, GraphQL...) est une problématique courante où l'on se pose la question de typer son contrat c'est-à-dire de définir les types TypeScript des entrées/sorties de l'API. Pourtant, la littérature n'est pas prolixe en la matière. Nous verrons différentes approches, pour la plupart issues de mes expériences, chacune présentant des avantages et inconvénients. L'objectif de cette présentation n'est pas d'être exhaustif. Il s'agit de fournir différentes options afin de choisir la plus appropriée à ses besoins en fonction du contexte.
* Durée :
  - [ ] 10 minutes
  - [x] 20 minutes
  - [ ] 30 minutes
  - [ ] Autres, précisez:
* Niveau :
  - [ ] Débutant
  - [x] Intermédiaire
  - [ ] Avancé

## A propos de vous

* Nom et prénom : DENEAU Romain
* Twitter : @DeneauRomain
* Github : https://github.com/rdeneau

**Comment by spontoreau** [comment]
Merci pour cette proposition 👍

**Comment by spontoreau** [comment]
Salut Romain,

Es ce que tu serais dispo pour faire ton sujet le 3 juin au meetup?

Désolé pour le temps d'attente sur ta proposition, on était entrain de voir pour faire un event spécial et ça a un peu bousculer tout le planning!

**Comment by rdeneau** [comment]
Salut Sylvain,

Le lundi 3 juin me convient tout à fait : je suis dispo et cela me laisse suffisamment du temps pour préparer malgré les congés de mai ^^

@+

**Comment by spontoreau** [comment]
Super!

Merci pour ta réponse rapide ;)

**Comment by paulsouche** [comment]
Hello désolé mais erreur de notre part, on va faire ca le 4 juin... Toujours dispo ?

**Comment by rdeneau** [comment]
J'avais confirmé sur Twitter. Je reporte ici la confirmation pour le mardi 4 juin. Je pense qu'on peut fermer l'issue.
