### ISSUE TITLE
Typed, Declarative, Data-Driven Routing for Node.js

### ISSUE THREAD

**Issue by zaiste** [ParisTypeScript/talks#20]
# Talk proposal - Paris TypeScript

## Talk description
* Title: **Typed, Declarative, Data-Driven Routing for Node.js**
* Content: 

Let's use TypeScript to build **declarative**, **data-driven** routing for Node.js. We will be declaring routes using the existing data structures - an approach *stolen* from the Clojure community. This way, we will limit the number of abstractions. On top of that, the type system will help us to control the shape of our routing. As a result, our code will be not only simple and straightforward, but also much easier to test and maintain.

* Duration:
  - [ ] 5 minutes (Lightning talk)
  - [x] 10 minutes
  - [x] 20 minutes
  - [ ] 30 minutes
  - [ ] Other, please specify:
* Level:
  - [ ] Beginner
  - [x] Intermediate
  - [ ] Advanced

## About you

* Name: Jakub Neander
* Twitter: @zaiste

(I can do a 10 minut version or a 20 minut version of this talk)

**Comment by spontoreau** [comment]
Hello Jakub,

I know you proposal was made a long time ago when we were focus on streaming things, but this time is over and on our side we are now back on fully physical events at Paris. 

So I'm closing this proposal even if it was a really great one !
