### ISSUE TITLE
Hugging Face: Building the "GitHub of Machine learning", with Typescript 🤗

### ISSUE THREAD

**Issue by julien-c** [ParisTypeScript/talks#21]
# Talk proposal - Paris TypeScript

## Talk description
* Title:
Hugging Face: Building the "GitHub of Machine learning", with Typescript
* Content (Briefly describe the content of the presentation):

Hugging Face has built some of the most popular open source libraries for Machine learning (ML) and natural language processing (NLP), like the [`transformers`](https://github.com/huggingface/transformers) repo (50k stars on GitHub).

We raised $60M and we are a team of 100, in Paris, NYC, and all over the globe.

On top of our open source, we are building [huggingface.co](https://huggingface.co), a hosted platform for the community to share their ML models and datasets, and collaborate on the Future of AI 🔥 

The platform is built in Typescript and implements git hosting, browsing, ML model deployment, as well as a ton of other capabilities, at scale, all in Typescript.

In this short talk I'll present the challenges and the lessons we learnt in the past few years.

* Duration:
  - [ ] 5 minutes (Lightning talk)
  - [ ] 10 minutes
  - [x] 20 minutes
  - [ ] 30 minutes
  - [ ] Other, please specify:
* Level:
  - [ ] Beginner
  - [x] Intermediate
  - [ ] Advanced

## About you
* Name: Julien Chaumond
* Twitter: [https://twitter.com/julien_c](julien-c)
* Company: CTO @huggingface

**Comment by spontoreau** [comment]
Thanks for you proposal!
