### ISSUE TITLE
Génération d'un SDK Typescript à partir de Protobuf

### ISSUE THREAD

**Issue by Vinzius** [ParisTypeScript/talks#24]
# Proposition de talk - Paris TypeScript

## Description du talk
* Titre : Génération d'un SDK Typescript à partir de Protobuf
* Contenu (Décrivez brièvement le contenu de la présentation) : 

Il devient parfois nécessaire d'automatiser la génération de ses outils (à défaut de les écrire manuellement). Quid de la génération d'un SDK Typescript à partir de Protocol Buffers? Overview des outils, du process, et des éléments spécifiques à Typescript.

* Durée :
  - [ ] 5 minutes (Lightning talk)
  - [ ] 10 minutes
  - [x] 20 minutes
  - [ ] 30 minutes
  - [ ] Autres, précisez:
* Niveau :
  - [x] Débutant
  - [x] Intermédiaire
  - [ ] Avancé

## A propos de vous
* Nom et prénom : GERMAIN Vincent
* Twitter : @vinzius
* Entreprise : Scaleway

**Comment by spontoreau** [comment]
Hello Vincent, merci pour ta proposition !

**Comment by Vinzius** [comment]
Salut Sylvain, bon pour moi !

**Comment by spontoreau** [comment]
Hello Vincent,

Malheureusement on ne va pas être en mesure de faire le meetup la semaine prochaine.
Du coup le prochain aura lieux début septembre (la date est à définir). Je te tiens au courant !

**Comment by spontoreau** [comment]
Hello Vincent,

C'est enfin le retour du meetup le 22 novembre... après une longue pause ^^'

Es ce que tu es intéressé pour venir faire ton talk ?

**Comment by Vinzius** [comment]
Hello,
Carrément !
Je te ping en MP pour les détails ^^
A bientôt
