### ISSUE TITLE
Mettre en place une stratégie de suppression du code mort avec ts-prune

### ISSUE THREAD

**Issue by hduprat** [ParisTypeScript/talks#26]
# Proposition de talk - Paris TypeScript

## Description du talk
* Titre : Mettre en place une stratégie de suppression du code mort avec ts-prune
* Contenu (Décrivez brièvement le contenu de la présentation) :  
Beaucoup de code mort dans une codebase, ça peut être frustrant. En tout cas, ça l’était pour moi.  
Dans ce talk, je présente l'outil **ts-prune** qui permet de lister les exports inutilisés dans un projet Typescript, et une stratégie pour se débarrasser efficacement du code mort ainsi que d'empêcher son retour.
* Durée :
  - [ ] 5 minutes (Lightning talk)
  - [ ] 10 minutes
  - [x] 20 minutes
  - [ ] 30 minutes
  - [ ] Autres, précisez:
* Niveau :
  - [x] Débutant
  - [x] Intermédiaire
  - [ ] Avancé

## A propos de vous
* Nom et prénom : Hugo Duprat
* Twitter : [@req__](https://twitter.com/req__)
* Entreprise : BAM

**Comment by spontoreau** [comment]
Salut Hugo, merci pour cette proposition !

**Comment by spontoreau** [comment]
Hello Hugo,

On penses faire le prochain meetup le 14 juin, es ce que tu serais dispo ?

**Comment by hduprat** [comment]
Hello @spontoreau, malheureusement je ne serai pas en France à cette date !

**Comment by hduprat** [comment]
@spontoreau tu as une date pour la prochaine édition ?

**Comment by spontoreau** [comment]
Hello !

C'est en cours de discussion pour faire un meetup en octobre ;)

**Comment by spontoreau** [comment]
Hello Hugo, je reviens enfin vers toi !

Désolé pour l'attente, la reprise a pris du temps. On organise un meetup le 22 novembre, es ce que tu serais disponible et toujours intéressé pour parler de ce sujet ?

**Comment by hduprat** [comment]
Hello @spontoreau ,

Aucun problème pour le 22 novembre 👍

**Comment by spontoreau** [comment]
Hello Hugo, tu peux me donner ton email (je te follow sur Twitter si tu veux m'envoyer un mp)

On va faire une tentative de stream pour le meetup, donc j'aimerais te partager quelques details sur le sujet ;)

**Comment by hduprat** [comment]
Je n'arrive pas à t'envoyer de mp sur Twitter pour une raison qui m'échappe donc je te réponds ici :) mon mail est hugo.duprat@gmail.com
