### ISSUE TITLE
Développer une application distribuée en JavaScript avec Temporal

### ISSUE THREAD

**Issue by maelropars** [ParisTypeScript/talks#28]
* Titre : Développer une application distribuée en TypeScript avec Temporal

* Contenu (Décrivez brièvement le contenu de la présentation) :
Le projet OpenSources Temporal, est un framework de "Durable Code Execution." Il permet d'exécuter du code de manière durable: en persistant chaque étape d'exécution, il rend possible la reprise en en cas d'incident ou de bug. 
Il garanti aussi les appels de systèmes externes, en assurant les "retry / timeout" automatiquement. Cela permet au développeur de faire abstraction de la complexité des applications distribuées et de se concentrer sur l'essentiel du code, en Typescript. 

En format Deep Dive, cela permet de passer plus de temps sur une démonstration en live coding. 

* Durée :
  - [ ] Lightning (10 minutes)
  - [x] Regular (20 minutes)
  - [x] Deep dive (40 minutes)
  
* Niveau :
  - [ ] Débutant
  - [x] Intermédiaire
  - [ ] Avancé

## A propos de vous
* Nom et prénom : Mael Ropars
* Github : https://github.com/temporalio/temporal
* Entreprise : Temporal Technologies

**Comment by spontoreau** [comment]
Hello Mael,

Merci pour ta proposition ! Je reviens vers toi ASAP

**Comment by spontoreau** [comment]
Hello Mael,

On va organiser un meetup le 31 janvier, es ce que tu serais dispo et toujours chaud pour faire une présentation (au format regular) ?

**Comment by maelropars** [comment]
Salut Sylvain,

oui ce serait ok pour moi !
Par format regular tu entends quoi exactement ? un format sur place avec
projection sur écran etc ?

Mael

**Comment by spontoreau** [comment]
Hello Mael,

Regular = 20 minutes + question réponse !

Tu avais proposé aussi de faire un deep dive, mais on ne prend plus trop ce genre de format. En fait c'est trop long pour un meetup, souvent les personnes décrochent. Du coup on préfére des petits sujets histoire de varier et de garder l'attention de tout le monde jusqu'au bout ;)

**Comment by maelropars** [comment]
ok je comprends c'est une bonne idée.
Pas de soucis pour moi, j'ai une version courte qui peut tenir en 20mn
(intro + démo).

**Comment by spontoreau** [comment]
Hello Mael, comment ça va ?

On est entrain de schedule le meeting. J'aurais besoin de ton email pour t'envoyer le lien et les infos pour le stream le jour J. Tu es sur un réseau en particulier ? LinkedIn ou Twitter ?

**Comment by maelropars** [comment]
Bonjour Sylvain

Tout va bien merci et toi ?
Mon mail est ***@***.*** et mon linkedin est
https://www.linkedin.com/in/mropars

Mael

**Comment by maelropars** [comment]
Bonjour Paul

est-ce que ce serait en présentiel ? Je peux être disponible oui.
A+
Mael

**Comment by paulsouche** [comment]
Désolé je manque à tout mes devoirs... Le meetup est en présentiel chez Microsoft. Les [infos sur l'event](https://www.meetup.com/fr-FR/paris-typescript/events/293016030/). I va y avoir une présentation par Microsoft en interne. J'attends ton go pour te rajouter au line up :pray: .

**Comment by maelropars** [comment]
Pas de soucis.
Oui je serai très intéressé de pouvoir passer faire une présentation ce
jour là !

**Comment by paulsouche** [comment]
OK ! Je vais te rajouter au line up. En fonction des autres speakers, on peut te demander de switcher de regular à deep dive ? Je ne pense pas que l'on aura le temps pour le deep dive mais juste pour savoir :pray:

**Comment by maelropars** [comment]
oui pas de problème j'ai un contenu assez extensible :)

**Comment by maelropars** [comment]
Merci à tous pour la très bonne organisation de ce meetup ! Je
recommanderai vivement à mes contacts de proposer des présentations à la
communauté Typescript Paris !
A bientôt j'espère
Mael

**Comment by spontoreau** [comment]
Merci à toi Mael pour ton talk trés intéressant !

A bientôt,
Sylvain
