### ISSUE TITLE
Exécuter le même code sur différents runtimes avec l'IOC

### ISSUE THREAD

**Issue by c100k** [ParisTypeScript/talks#29]
# Proposition de talk - Paris TypeScript

## Description du talk
* Titre : Exécuter le même code sur différents runtimes avec l'IOC

* Contenu (Décrivez brièvement le contenu de la présentation) :

Aujourd'hui on peut écrire du code serveur (Node) et client (React, React Native, CLI) en TypeScript. Dans pas mal de codebases, le même code est souvent dupliqué car les dépendances ne sont pas les mêmes. Or, il y a des solutions pour cela et l'IOC en fait partie. Tour d'horizon par l'exemple expliquant comment la mettre en place.

* Durée :
  - [ ] Lightning (10 minutes)
  - [x] Regular (20 minutes)
  - [ ] Deep dive (40 minutes)
  > ⚠️ merci de préciser dans la description pourquoi vous avez besoin d'un format deep dive pour présenter votre sujet

* Niveau :
  - [ ] Débutant
  - [x] Intermédiaire
  - [ ] Avancé

## A propos de vous
* Nom et prénom : Chafik H'NINI
* Twitter : [https://twitter.com/c100k_](https://twitter.com/c100k_)
* Entreprise : Freelance

**Comment by spontoreau** [comment]
Hello, du coup ton sujet est accepté :tada: !

On va devoir décaler le meetup au 7 février et nous voudrions répartir ton sujet et le #31  sur deux meetup distinct. Donc on voulait savoir si tu étais dispo pour choisir par la suite lequel des 2 nous faisons passer en premier ;)

**Comment by spontoreau** [comment]
Hello,

N'ayant pas de nouveau pour le sujet Hexagonal Archi, je me permets de te demander si tu serais chaud pour faire le tiens au prochain meetup ? (29 mars: https://www.meetup.com/Paris-Typescript/events/292026642/)

Bonne journée à toi !

**Comment by c100k** [comment]
Allez !

**Comment by spontoreau** [comment]
Ok top !

Merci pour ta réponse je t'ajoute dans le lineup ;)
