### ISSUE TITLE
C-c-c-c'est l'heure du-du-du-du duel !! Avec TS et BabylonJs

### ISSUE THREAD

**Issue by MTerance** [ParisTypeScript/talks#3]
# Proposition de talk - Paris TypeScript

## Description du talk
* Titre : "C-c-c-c'est l'heure du-du-du-du duel !! Avec TS et BabylonJs" ou 
"Comment creer un Trading Card Game avec TS et Babylon"

* Contenu (Décrivez brièvement le contenu de la présentation) :
Faire des jeux sur navigateur n'a jamais ete aussi simple qu'en ce moemnt !
Sur cette presentation , nous allons aborder la programmation 3D en TS en utilisant la moteur 3D
BabylonJs , crée par David Catuhe, David Rousset et Sebastien Vandenberghe.
Et comme exemple pourquoi pas faire une jeu de carte ?!

* Durée :
  - [ ] 10 minutes
  - [ ] 20 minutes
  - [ ] 30 minutes
  - [X] Autres, précisez: 25 min
* Niveau :
  - [X] Débutant
  - [X] Intermédiaire
  - [ ] Avancé

## A propos de vous

* Nom et prénom : Moussoki Terance
* Twitter : 
* Entreprise : Expaceo

**Comment by spontoreau** [comment]
Salut Térance, merci pour ta proposition!

Enfin un talk Babylon à Paris TypeScript, ça fait plaisir :p

**Comment by spontoreau** [comment]
Salut Terance, ça va?

Es ce que tu serais dispo le 3 juin pour faire ton talk au meetup?

**Comment by MTerance** [comment]
Pas de souci pour moi, même si ce sera plus un talk pour débutants sur
Typescript.
De plus il faut que l'on se voit pour la partie retransmission s de Paris TS

Le lun. 8 avr. 2019 à 18:04, Sylvain PONTOREAU <notifications@github.com> a
écrit :

**Comment by paulsouche** [comment]
Hello désolé mais erreur de notre part, on va faire ca le 4 juin... Toujours dispo ?

**Comment by MTerance** [comment]
Oui toujours dispo.

**Comment by paulsouche** [comment]
Super on va annoncer l'event avec ton talk très prochainement

**Comment by spontoreau** [comment]
Thank you @MTerance !
