### ISSUE TITLE
Staging is dead. Long live (full-stack) previews.

### ISSUE THREAD

**Issue by raoufchebri** [ParisTypeScript/talks#30]
# Proposition de talk - Paris TypeScript

## Description du talk
* Titre : Staging is dead. Long live (full-stack) previews.

* Contenu (Décrivez brièvement le contenu de la présentation) : in this talk, we’ll discuss how Vercel, Prisma and database branching can enable full-stack previews. Imagine you make changes to your database schema that are not reflected in your preview. One way to solve this is to provision another database. But that takes time (tens of minutes) and will likely increase your CI/CD cost.

* Durée :
  - [ ] Lightning (10 minutes)
  - [x] Regular (20 minutes)
  - [ ] Deep dive (40 minutes)
  > ⚠️ merci de préciser dans la description pourquoi vous avez besoin d'un format deep dive pour présenter votre sujet

* Niveau :
  - [ ] Débutant
  - [x] Intermédiaire
  - [ ] Avancé

## A propos de vous
* Nom et prénom : Raouf Chebri
* Twitter : @raoufdevrel 
* Entreprise : Neon

**Comment by spontoreau** [comment]
Hello Raouf, how are you ?

Your talk is under review and we are talking about it with other organizers. We have the feeling that this topic is more linked to CI/CD topic that TypeScript development. On the opposite it's an interesting subject and talking about Prisma is something that can be really valuable for attendees (and we are looking for more talks regarding Prisma).

Can you give us some details about what you gonna show during your talk ?

Thanks in advance,
Sylvain

**Comment by raoufchebri** [comment]
Hi Sylvain,

Thanks for reaching out and the feedback. I can certainly have a Prisma angle to the talk. Can you tell me more about the audience? What would they want to see?

Thanks,
Raouf

From: Sylvain PONTOREAU ***@***.***>
Date: Wednesday, 25 January 2023 at 13:17
To: ParisTypeScript/talks ***@***.***>
Cc: Raouf Chebri ***@***.***>, Author ***@***.***>
Subject: Re: [ParisTypeScript/talks] Staging is dead. Long live (full-stack) previews. (Issue #30)

Hello Raouf, how are you ?

Your talk is under review and we are talking about it with other organizers. We have the feeling that this topic is more linked to CI/CD topic that TypeScript development. On the opposite it's an interesting subject and talking about Prisma is something that can be really valuable for attendees (and we are looking for more talks regarding Prisma).

Can you give us some details about what you gonna show during your talk ?

Thanks in advance,
Sylvain

**Comment by raoufchebri** [comment]
Or event better, I could speak about Kysely https://github.com/koskimas/kysely

From: Raouf Chebri ***@***.***>
Date: Thursday, 26 January 2023 at 08:15
To: ParisTypeScript/talks ***@***.***>, ParisTypeScript/talks ***@***.***>
Cc: Author ***@***.***>
Subject: Re: [ParisTypeScript/talks] Staging is dead. Long live (full-stack) previews. (Issue #30)
Hi Sylvain,

Thanks for reaching out and the feedback. I can certainly have a Prisma angle to the talk. Can you tell me more about the audience? What would they want to see?

Thanks,
Raouf

From: Sylvain PONTOREAU ***@***.***>
Date: Wednesday, 25 January 2023 at 13:17
To: ParisTypeScript/talks ***@***.***>
Cc: Raouf Chebri ***@***.***>, Author ***@***.***>
Subject: Re: [ParisTypeScript/talks] Staging is dead. Long live (full-stack) previews. (Issue #30)

Hello Raouf, how are you ?

Your talk is under review and we are talking about it with other organizers. We have the feeling that this topic is more linked to CI/CD topic that TypeScript development. On the opposite it's an interesting subject and talking about Prisma is something that can be really valuable for attendees (and we are looking for more talks regarding Prisma).

Can you give us some details about what you gonna show during your talk ?

Thanks in advance,
Sylvain

**Comment by spontoreau** [comment]
Hello,

Regarding the audience it's most of the time a full room of developers, so topics on libraries or frameworks are always interesting.

The two topics you propose seem to me very good too, so it's up to you. They will clearly interest the attendees 😉

**Comment by raoufchebri** [comment]
Awesome, Would this work for you?

Title: Type-safe queries at the edge with Kysely.
Description: In this talk, we will explore Kysely, the typescript SQL query builder and discuss the differences with ORMs such as Prisma. We will also see how to run Kysely at the edge.

Please let me know what you think.
Best,
Raouf

From: Sylvain PONTOREAU ***@***.***>
Date: Monday, 30 January 2023 at 09:16
To: ParisTypeScript/talks ***@***.***>
Cc: Raouf Chebri ***@***.***>, Author ***@***.***>
Subject: Re: [ParisTypeScript/talks] Staging is dead. Long live (full-stack) previews. (Issue #30)

Hello,

Regarding the audience it's most of the time a full room of developers, so topics on libraries or frameworks are always interesting.

The two topics you propose seem to me very good too, so it's up to you. They will clearly interest the attendees 😉

**Comment by spontoreau** [comment]
Sounds good to me :)

**Comment by paulsouche** [comment]
@raoufchebri Hello ! Next event is the 16th of May at Microsoft. Are you available ?
