### ISSUE TITLE
L'architecture hexagonale en pratique avec TS

### ISSUE THREAD

**Issue by Arnoid31** [ParisTypeScript/talks#31]
# Proposition de talk - Paris TypeScript

## Description du talk
* Titre : L'architecture hexagonale en pratique avec TS

* Contenu : L'architecture hexagonale, tout le monde en parle (et à raison), mais il peut être compliqué de s'y mettre tant qu'on a pas vu de mise en pratique. Ce talk est l'occasion de mieux comprendre pourquoi et comment commencer, en s'appuyant sur un exemple métier.

* Durée :
  - [ ] Lightning (10 minutes)
  - [x] Regular (20 minutes)
  - [ ] Deep dive (40 minutes)

* Niveau :
  - [ ] Débutant
  - [x] Intermédiaire
  - [ ] Avancé

## A propos de vous
* Nom et prénom : Arnaud Commelin
* LinkedIn : https://www.linkedin.com/in/%F0%9F%A6%84-arnaud-commelin-ab148734/
* Entreprise : Swan.io (en freelance)

**Comment by spontoreau** [comment]
Hello, du coup ton sujet est validé par l'orga :pinata: !

On décale le prochain Paris TypeScript au 7 février et nous voudrions répartir ton sujet et le #29 sur deux meetup distinct. 

Es ce que tu serais dispo pour savoir si nous faisons passer le tiens en premier ?

**Comment by Arnoid31** [comment]
Hello ! Pas de souci pour faire passer mon talk le 7 février :)

**Comment by c100k** [comment]
Hello, je réponds ici pour centraliser la discussion :)

Effectivement les 2 sujets peuvent être liés. Pas de souci pour passer le mien au meetup d'après du coup. Comme ça je pourrai adapter et éviter les répétitions.

**Comment by spontoreau** [comment]
Hello messieurs, merci @c100k pour avoir partagé l'info sur cette issue, on fait comme ça pas de soucis ;)

@Arnoid31 je vais changer le schedule du meetup aujourd'hui et te placer dans le lineup !

**Comment by Arnoid31** [comment]
Du coup au niveau schedule, le meetup de demain est maintenu ou pas ?

**Comment by spontoreau** [comment]
Hello, désolé pour le retard :neutral_face: 

Hélas non pas maintenu, on te tiens au courant quand on a un peu plus de visu !

**Comment by spontoreau** [comment]
Hello je reviens vers toi, on a une date en ligne de vue : 22 mars.

Es ce que ça peut le faire pour toi ?

**Comment by spontoreau** [comment]
Hello, on vient d'annoncer le meetup pour le 29: https://www.meetup.com/Paris-Typescript/events/292026642/

Tiens moi au courant si tu es chaud pour faire ton sujet ce jour là ;)

**Comment by laurentpayot** [comment]
@Arnoid31 pour le 29 tu seras là ou pas ? :eyes:

**Comment by Arnoid31** [comment]
Hello ! Désolé pour le temps de réponse. Je ne peux pas garantir ma présence le 29, et jusqu'à mi-mai, donc let's report that si ça ne vous ennuie pas.

**Comment by paulsouche** [comment]
@Arnoid31 prochaine date le 10 octobre chez Theodo. Dispo ?

**Comment by paulsouche** [comment]
@Arnoid31 prochaine date le 10 septembre chez Takima. Dispo ?
