### ISSUE TITLE
What we never thought could be possible with never

### ISSUE THREAD

**Issue by speray** [ParisTypeScript/talks#36]
# Proposition de talk - Paris TypeScript

## Description du talk
* Titre : What we never thought could be possible with never. ("Ne jamais dire never" en francais peut etre?)

* Contenu (Décrivez brièvement le contenu de la présentation) :

Le type never n'apparait pas souvent dans les codebases, mais il a pourtant pas mal de cas d'utilisations concrets qui peuvent se révéler très utiles. Nous regarderons des exemples ou l’utilisation de never permet améliorer le typage ou de créer des transformations de types complexes.

* Durée :
  - [ ] Lightning (10 minutes)
  - [x] Regular (20 minutes)
  - [ ] Deep dive (40 minutes)
  > ⚠️ merci de préciser dans la description pourquoi vous avez besoin d'un format deep dive pour présenter votre sujet

* Niveau :
  - [ ] Débutant
  - [x] Intermédiaire
  - [ ] Avancé

## A propos de vous
* Nom et prénom : Peray Sebastien
* Twitter :
* Entreprise : Microsoft

**Comment by paulsouche** [comment]
Hello ! Merci pour l'abstract on t'a rajouté au [line up](https://www.meetup.com/fr-FR/paris-typescript/events/293016030)

**Comment by speray** [comment]
@paulsouche Merci! Dans le titre du lineup, peut on garder soit la version francaise, soit l'anglaise, mais les 2 c'est un peu bizarre :)
