### ISSUE TITLE
Coder un escape game avec Typescript et WorkAdventure

### ISSUE THREAD

**Issue by moufmouf** [ParisTypeScript/talks#37]
# Proposition de talk - Paris TypeScript

## Description du talk
* Titre : Coder un escape game avec Typescript et WorkAdventure

* Contenu (Décrivez brièvement le contenu de la présentation) :

C'est l'été, pourquoi ne pas se détendre un peu en codant un un jeu?
Dans cette présentation, je vous propose de détourner le fonctionnement de WorkAdventure (une plateforme de remote-work) pour coder un escape-game en Typescript. Nous verrons le fonctionnement de l'architecture de scripting Typescript et coderons (en live!) un donjon dans lequel il faut être 3 joueurs qui coopèrent pour avoir la moindre chance de s'enfuir!

* Durée :
  - [ ] Lightning (10 minutes)
  - [x] Regular (20 minutes)
  - [ ] Deep dive (40 minutes)
  > ⚠️ merci de préciser dans la description pourquoi vous avez besoin d'un format deep dive pour présenter votre sujet

* Niveau :
  - [x] Débutant
  - [ ] Intermédiaire
  - [ ] Avancé

## A propos de vous
* Nom et prénom : David Négrier
* Twitter : @david_negrier
* Entreprise : WorkAdventure

## Note

La présentation ne fait pas appel à des notions avancées de Typescript (je peux proposer pleins d'autres idées de présentation sur du typage avancé si vous préférez). Elle est donc plutôt adaptée à des débutants (on parle un peu typage, type "unknown", tool-chain vite. Elle est très ludique par contre!

Le but est d'arriver à ce résultat à la fin de la session: https://play.workadventu.re/_/p46u7poy7s8/moufmouf.github.io/programmez-escape-game/map.tmj (à tester à 3!)
La présentation est dérivée d'un article qui sera publié dans le numéro d'été de Programmez!

**Comment by spontoreau** [comment]
Salut David, trés sympa ton sujet !

Je te tiens au courant ;)

**Comment by spontoreau** [comment]
Hello @moufmouf, ça te dirait de faire ton talk au prochain meetup (27 juin). Il nous reste un slot de libre.

Bonne journée,
Sylvain

**Comment by moufmouf** [comment]
Avec plaisir!

**Comment by spontoreau** [comment]
Ok super !

Je t'ajoute au lineup, merci ;)
