### ISSUE TITLE
Effect : une solution efficace aux problèmes de software engineering

### ISSUE THREAD

**Issue by antoine-coulon** [ParisTypeScript/talks#38]
# Proposition de talk - Paris TypeScript

## Description du talk
* Titre : Effect, une solution efficace aux problèmes de software engineering

* Contenu (Décrivez brièvement le contenu de la présentation) :

[Effect](https://www.effect.website/) est une boîte à outils TypeScript qui permet de répondre aux problèmes les plus communs que l’on rencontre lors du développement d’applications, tels que la résilience, la composabilité, la gestion de la concurrence et la maintenabilité du code.

Dans ce talk je présenterai ces problèmes et je montrerai comment Effect les résout de manière efficace avec des exemples.    

* Durée :
  - [ ] Lightning (10 minutes)
  - [X] Regular (20 minutes)
  - [ ] Deep dive (40 minutes)
  > ⚠️ merci de préciser dans la description pourquoi vous avez besoin d'un format deep dive pour présenter votre sujet

* Niveau :
  - [ ] Débutant
  - [X] Intermédiaire
  - [ ] Avancé

## A propos de vous
* Nom et prénom : Coulon Antoine
* Twitter : [@c9antoine](https://twitter.com/c9antoine)
* Entreprise : TCM Labs

**Comment by spontoreau** [comment]
Hello Antoine, merci pour ta proposition. On revient vers toi d'ici peu ;)

**Comment by paulsouche** [comment]
Hello @antoine-coulon prochain meetup le 10 octobre chez Theodo. Dispo ?

**Comment by antoine-coulon** [comment]
Hello @paulsouche, il y avait des discussions en cours avec @spontoreau sur un probable hosting chez nous en décembre, auquel cas ce talk y serait présenté. J'essaye de recouper l'information au plus vite pour te confirmer cela d'ici demain soir.

**Comment by spontoreau** [comment]
Hello 👋

Je t'ai envoyé un mp sur twitter pour l'organisation du meetup de décembre, mais je n'ai pas reçu de réponse alors je me permets de t'envoyer un message sur ta proposition de talk.

Bonne journée,
Sylvain

**Comment by antoine-coulon** [comment]
Hello @spontoreau, 

Désolé pour le délai de réponse. 

On te confirme ça dans l'après-midi mais a priori toujours ok.

Antoine

**Comment by jbmusso** [comment]
Hello @spontoreau -- c'est ok pour nous dans nos bureaux en décembre (métro Grands Boulevards).

(J'avais oublié l'existence de ce repo GitHub, très pratique !)

**Comment by spontoreau** [comment]
Pas de soucis, merci pour votre réponse ! Très cool 😎

Je reviens vers vous quand on a préparé le draft du meetup pour faire l'annonce !

A bientôt ;)
