### ISSUE TITLE
How we leveraged TypeScript to bring a new developer experience to Node.js background jobs

### ISSUE THREAD

**Issue by charlypoly** [ParisTypeScript/talks#39]
# Talk proposal - Paris TypeScript

## Talk description
* Title:
How we leveraged TypeScript to bring a brand new experience to Node.js background jobs

* Content (Briefly describe the content of the presentation):
How to disrupt the principles of queueing and bring a brand-new developer experience?
For Node.js, the solution was found with the help of TypeScript's Generics and Mapped Types.
Let's deep dive in the `@defer/client` and `@defer/client/next` types 🕳️ ✨ 

* Duration:
  - [ ] Lightning (10 minutes)
  - [x] Regular (20 minutes)
  - [ ] Deep dive (40 minutes)
  > ⚠️ please specify in the description why you need a deep dive format to present your topic

* Level:
  - [ ] Beginner
  - [x] Intermediate
  - [ ] Advanced

## About you
* Name: Charly Poly
* Twitter: https://twitter.com/whereischarly
* Company: Defer

**Comment by spontoreau** [comment]
Hello Charly !

Merci pour ta proposition, je te tiens au courant ;)

**Comment by paulsouche** [comment]
Hello @charlypoly. Prochain event le 10 octobre chez Theodo. Dispo ?

**Comment by charlypoly** [comment]
@paulsouche Yes, dispo !

**Comment by spontoreau** [comment]
Trop cool, merci Charly !
