### ISSUE TITLE
Tout ce que vous devriez savoir sur Unicode, UTF-8 et autres 

### ISSUE THREAD

**Issue by dubzzz** [ParisTypeScript/talks#4]
# Proposition de talk - Paris TypeScript

## Description du talk
* Titre : Tout ce que vous devriez savoir sur Unicode, UTF-8 et autres 
* Contenu (Décrivez brièvement le contenu de la présentation) : La string est l'une des primitives principales en informatique, et ce quelque soit le langage. Pourtant, derrière son semblant de simplicité, se cache une énorme complexité inhérente aux spécifications Unicode. Ce talk a pour objectif de vous présenter ce que sont Unicode, UTF-8.. Afin que vous soyez prêt pour l'internationalisation de vos Apps. 
* Durée :
  - [ ] 10 minutes
  - [x] 20 minutes
  - [ ] 30 minutes
  - [ ] Autres, précisez:
* Niveau :
  - [x] Débutant
  - [ ] Intermédiaire
  - [ ] Avancé

## A propos de vous

* Nom et prénom : Dubien Nicolas 
* Twitter : ndubien 
* Entreprise : Criteo

**Comment by spontoreau** [comment]
Salut Nicolas, merci pour ta proposition 👍

**Comment by spontoreau** [comment]
Salut Nicolas, tu vas bien?
Es ce que tu serais dispo le 3 juin pour faire ton talk au prochain meetup? 

(celui de mai a été annulé pour privilégier une spéciale le 23 avril)

**Comment by dubzzz** [comment]
Disponible le 3 Juin

**Comment by spontoreau** [comment]
👍

**Comment by spontoreau** [comment]
@dubzzz hey Nico, don't know if you still want to do this talk (keep me in touch)

**Comment by dubzzz** [comment]
Yep, still wanting to do it

**Comment by spontoreau** [comment]
Hello Nico,

A priori tu as fais un sujet similaire à Paris.js, donc hésites pas à nous faire signe si tu veux le refaire ;)

A bientôt !

**Comment by spontoreau** [comment]
@dubzzz comment ça va Nico ?

Es ce que ça te va si je close cette issue ? C'est une proposition de longue date et je ne sais pas si tu auras un jour l'occaz de faire ce sujet à Paris TypeScript (à toi de me dire)

**Comment by spontoreau** [comment]
Ok merci pour ta réponse. Du coup je close pas.

On va préparer le planning pour les prochains d'ici peu. Je te tiens au courant !

**Comment by paulsouche** [comment]
@dubzzz Le prochain meetup est le 16 mai chez Microsoft. Est ce que par hasard ca le ferait ?

**Comment by dubzzz** [comment]
Ah non. Je serai sur Paris la semaine juste avant et celle juste après mais pas celle-ci désolé
