### ISSUE TITLE
Crossing the bridge: seamless strategies for updating and migrating libraries

### ISSUE THREAD

**Issue by gpichot** [ParisTypeScript/talks#41]
# Proposition de talk - Paris TypeScript

## Description du talk
* Titre : Crossing the bridge: seamless strategies for upadting and migrating libraries
En français: "Stratégies pour la mise à jour et la migration de bibliothèques sans accroc"

* Contenu  :
Sur ma dernière mission, j'ai mené plusieurs chantiers de modernisation d'une stack front et back existante : mises à jour des versions de librairies (mongoose/mongodb, react query, webpack -> vite etc.) et continuer la conversion d'une code base JS/TS non strict vers TypeScript strict.
Ce talk est donc un REX sur la gestion du changement technique d'un projet et fournis des pistes de pour réaliser les mises à jour des librairies tierces et migrer son code de JavaScript vers TypeScript sans accroc.

* Durée :
  - [ ] Lightning (10 minutes)
  - [x] Regular (20 minutes)
  - [ ] Deep dive (40 minutes)

Il faut que je mette à plat par slides pour savoir combien de temps exactement ça va prendre.

* Niveau :
  - [ ] Débutant
  - [x] Intermédiaire
  - [ ] Avancé

## A propos de vous
* Nom et prénom : Gabriel Pichot
* Links: [Previous Talks & Workshops](https://github.com/gpichot/talks) [LinkedIn](https://www.linkedin.com/in/gabrielpichot/?originalSubdomain=fr) 
* Entreprise : Solo my own company [CraftValue](https://www.craftvalue.io)

**Comment by spontoreau** [comment]
Hello Gabriel :wave: 

Merci pour ta propostion, on revient vers toi d'ici peu !

**Comment by spontoreau** [comment]
Hello Gabriel, avec un peu de retard je reviens vers toi pour ta présentation.

Es ce que tu serais dispo pour la faire le mardi 13 février ?

**Comment by gpichot** [comment]
@spontoreau Si c'est central ce sera bon : par contre il y a de fortes chances que j'arrive un peu après 19h le temps du trajet.

**Comment by spontoreau** [comment]
Hello, on commence généralement vers 19h15.

Je peux te mettre en dernier dans le lineup. Pour info c'est central à côté St Lazard.

**Comment by gpichot** [comment]
Hello @spontoreau parfait dans ce cas !

**Comment by spontoreau** [comment]
Ok super, je te rajoute au lineup !
