### ISSUE TITLE
Comment ma config Typescript m’évite des dizaines de bugs

### ISSUE THREAD

**Issue by Eszik** [ParisTypeScript/talks#42]
# Proposition de talk - Paris TypeScript

## Description du talk
* Titre : 

**Comment ma config Typescript m’évite des dizaines de bugs**

* Contenu (Décrivez brièvement le contenu de la présentation) :

Typescript s’est imposé sur de nombreux projets web comme indispensable pour éviter les bugs avant même de déployer son code. Mais j’ai été plusieurs fois surpris par de légères différences de fonctionnement de Typescript d’une codebase à une autre. Par exemple, une équipe rencontrait régulièrement la redoutée “TypeError: Cannot read property of undefined” alors que Typescript les détectait correctement sur un autre projet.

La source de ces différences ? Le tsconfig.json, fichier de configuration parfois oublié qui abrite plusieurs paramètres clés pouvant rendre vos types plus précis et vous éviter encore plus de bugs.

Dans de ce talk, on verra par des exemples concrets comment des options telles que `noUncheckedIndexAccess` ou `useUnknownInCatchVariables` permettent de détecter des erreurs de typage supplémentaires. On verra aussi quelques techniques pour adapter une codebase déjà existante à ces nouvelles règles.

* Durée :
  - [ ] Lightning (10 minutes)
  - [X] Regular (20 minutes)
  - [ ] Deep dive (40 minutes)

* Niveau :
  - [ ] Débutant
  - [x] Intermédiaire
  - [ ] Avancé

## A propos de vous
* Nom et prénom : Thomas Bianco
* Twitter :
* Entreprise : [Theodo](https://www.theodo.fr/)

**Comment by spontoreau** [comment]
Salut Thomas, merci pour cette proposition. On revient vers toi rapidement !

**Comment by spontoreau** [comment]
Hello :wave: 

Es ce que tu serais dispo le mardi 13 février pour faire ton talk ?

Bonne journée,
Sylvain
