### ISSUE TITLE
Des specs métier typées avec TypeScript

### ISSUE THREAD

**Issue by c100k** [ParisTypeScript/talks#43]
# Proposition de talk - Paris TypeScript

## Description du talk
* Titre : Des specs métier typées avec TypeScript

* Contenu (Décrivez brièvement le contenu de la présentation) :

La blague veut que chaque jour voit un nouveau framework JavaScript sortir. C'est probablement vrai 😅 Ils ont, toutefois, tous le point commun de se concentrer sur la technique, et les détails d'implémentation. Mais peu sont faits pour faciliter le développement d'applications "de la vraie vie", d'applications métier. Et si on pouvait écrire des specs en TypeScript ?

Dans ce talk, l'idée est de présenter un concept, une idée, qui est encore au stade d'alpha (mais avec du code concret, bien sûr). Un peu à la manière de cet article https://0pointer.de/blog/projects/systemd.html.

* Durée :
  - [ ] Lightning (10 minutes)
  - [x] Regular (20 minutes)
  - [ ] Deep dive (40 minutes)
  > ⚠️ merci de préciser dans la description pourquoi vous avez besoin d'un format deep dive pour présenter votre sujet

* Niveau :
  - [ ] Débutant
  - [x] Intermédiaire
  - [ ] Avancé

## A propos de vous
* Nom et prénom : H'nini Chafik
* Twitter : N/A
* Entreprise : RebootX

**Comment by spontoreau** [comment]
Hello Chafik comment vas-tu ?

Je serais curieux de discuter de ton sujet lors du prochain meetup avant qu'on le review avec le orga (on va lancer l'orga pour en faire un le 13 février)

**Comment by c100k** [comment]
Salut Sylvain, avec plaisir. Dis moi comment tu veux en discuter et on planifie ça.

**Comment by c100k** [comment]
Je me permets de fermer car le projet a avancé et évolué depuis ;)
