### ISSUE TITLE
Why I love TypeScript in React

### ISSUE THREAD

**Issue by spanarin** [ParisTypeScript/talks#45]
# Talk proposal - Paris TypeScript

## Talk description
* Title: Why I love TypeScript in React

* Content (Briefly describe the content of the presentation): I’d like to highlight things that made my React development much easier with TypeScript - props typing, JSON data typing etc. 

* Duration:
  - [ ] Lightning (10 minutes)
  - [x] Regular (20 minutes)
  - [ ] Deep dive (40 minutes)
  > ⚠️ please specify in the description why you need a deep dive format to present your topic

* Level:
  - [x] Beginner
  - [ ] Intermediate
  - [ ] Advanced

## About you
* Name: Sergei Panarin
* Twitter: @spanarin
* Company: stealth AI startup

**Comment by spontoreau** [comment]
Hello Sergei how are you ?

Thanks for this proposal, I keep you in touch :wink:

**Comment by spanarin** [comment]
Hello Sylvain!All is good, thanks! Keep in touch,SergeiOn 1 Feb 2024, at 09:20, Sylvain PONTOREAU ***@***.***> wrote:﻿
Hello Sergei how are you ?
Thanks for this proposal, I keep you in touch 😉

**Comment by spontoreau** [comment]
Hello Sergei, a quick question for you : are you based in Paris ?

**Comment by spanarin** [comment]
Hello Sylvian!
Yes.

Best,
Sergei Panarin

**Comment by spontoreau** [comment]
Hello Sergei 👋

Sorry I'm late to answer you !

We want to do a special meetup on React in June (we are planning it). Will you be available on June 11th ?

**Comment by spanarin** [comment]
Hello Sylvain!Yes, June 11th works good for me. Best,SergeiOn 17 Apr 2024, at 21:30, Sylvain PONTOREAU ***@***.***> wrote:﻿
Hello Sergei 👋
Sorry I'm late to answer you !
We want to do a special meetup on React in June (we are planning it). Will you be available on June 11th ?

**Comment by spontoreau** [comment]
Excellent !

Thank you Sergei:)
