### ISSUE TITLE
Programmation Fonctionnelle: Guide anti-théologique

### ISSUE THREAD

**Issue by Akheloes** [ParisTypeScript/talks#46]
# Proposition de talk - Paris TypeScript

## Description du talk
* Titre : Programmation Fonctionnelle: Guide anti-théologique

* Contenu (Décrivez brièvement le contenu de la présentation) : Ce n'est qu'après 6 ans d'expérience en tant que développeur que je découvre la programmation fonctionnelle (FP en anglais), et pourtant, elle était là depuis toujours. En vérité, je l'avais déjà utilisée, sans trop le savoir, et nombreux d'entre vous l'avaient déjà utilisée sans doute. Loin des méandres d'un univers académico-mathématique, on regardera le sujet dans les fondamentaux, au menu:
- Aperçu ultra-rapide sur l'origine du sujet (théorie catégorielle, lambda calculus, etc.);
- Une définition (ou tentative de);
- OOP vs FP (round 1): situer l'audience par rapport à ce qu'ils connaissent au mieux;
- Fondamentaux: fonctions pures, sides-effects, stateful vs stateless, le déclaratif vs imperatif, immutabilité, laziness, etc.
- OOP vs FP (round 2): revenir en synthèse pour consolider le contraste; (Optional)
- Techniques et pattern: currying, functors, etc. (Optional)
- L'idée fondamentale à retenir.

Les parties optionnelles dépenderont beaucoup du rythème de questions interactives.

Le tout sera servi avec plein d'exemples de code et des memes !

* Durée :
  - [ ] Lightning (10 minutes)
  - [ ] Regular (20 minutes)
  - [x] Deep dive (40 minutes)
  > ⚠️ merci de préciser dans la description pourquoi vous avez besoin d'un format deep dive pour présenter votre sujet

Le deep dive est idéal pour ajouter des exemples codes et parler des patterns, mais si c'est pas possible, le sujet peut se refondre en format regular.

* Niveau :
  - [x] Débutant
  - [x] Intermédiaire
  - [ ] Avancé

## A propos de vous
* Nom et prénom : OUDBIB
* Twitter : -
* Entreprise : Kaibee

**Comment by laurentpayot** [comment]
En quel langage seront les exemples ? TypeScript ? (je suis passé à [F# qui est super pour la PF](https://learn.microsoft.com/fr-fr/dotnet/fsharp/tutorials/functional-programming-concepts))

**Comment by Akheloes** [comment]
> En quel langage seront les exemples ? TypeScript ? (je suis passé à [F# qui est super pour la PF](https://learn.microsoft.com/fr-fr/dotnet/fsharp/tutorials/functional-programming-concepts))

Les examples seront en TypeScript, on est certes pas pure functional (F# et Haskell sont quand même plus avancés), mais le but c'est de donner un aperçu sur comment un "débutant" peut pratiquer la FP sur TS sans forcément baver du jargon.

**Comment by spontoreau** [comment]
Hello @Akheloes merci pour ta proposition.

Il y a déjà eu un talk de 30 minute la dessus en 2019, donc pourquoi pas en refaire un (à l'époque on n'avait pas de stream ni de record). Les retours étaient partagés... L'introduction était bien pour tous les niveaux, mais la partie avancée était indigeste pour ceux qui démarrait en TypeScript. A côté de ça les dév expérimentés étaient ravis :smile:. 

Du coup si ça te va, je penses qu'un format regular avec la partie que tu proposes en round 1 ferait un bon talk pour la commu ;). Si les feedbacks sont positifs pourquoi pas faire un deuxiéme talk clairement identifié comme "advance" plus tard.

Qu'en penses tu ?

**Comment by Akheloes** [comment]
@spontoreau : la prez s'appellera "guide anti-théologique" pour signifier qu'on va éviter au max l'ésotérisme (qui me plait perso, mais franchement, pas nécessaire pour tout le monde et pour un usage pragmatique et au jour-au-jour - debatable, I know, mais une intro doit être simple).

Je dois vraiment rework la prez pour que ça rentre dans les 20 minutes, ça se fera alors sans les exemples de codes (ou très peu), donc ça peut être quick-blitz. Si ça vous va, ça me va, et puis je suis prêt à laisser mes slides pour usages publiques et continue rl'échange autour d'une bonne mousse :D

**Comment by Akheloes** [comment]
@spontoreau je vais me prêter à l'exercice des 20 minutes :), je peux bien perdre quelques parties en gardant l'essentiel et en essayant de donner envie d'aller voir les slides et les bouts de codes les moins cruciaux.

Si c'est un go pour vous: vous me direz une date et une estimation du nombre d'invités que je puisse bloquer le créneau et (essayer) d'avoir des pizzas pour tout le monde de la part de ma boîte (pas une promesse mais il y a très bon espoir de).

Merci et beau WE !

**Comment by spontoreau** [comment]
Hello comment ça va 👋

On va lancer l'orga du prochain meetup d'ici peu. Est ce que tu serais dispo le 14 mai ?

**Comment by Akheloes** [comment]
Oy !
Je serais absent presque tout le mois de Mai sauf la dernière semaine, si cette semaine n'est pas possible, on pourrait se prévoir Juin ou Aout (comme vous souhaitez). J'ai pas mal d'engagements (Podcasts et Meetups et Confs) en plus d'être à cheval entre Lyon et Paris donc n'hésitez pas à prévoir un peu à l'avance (même trois mois à l'avance en vrai, hehe).
Désolé et au plaisir de notre rencontre :) !

**Comment by spontoreau** [comment]
Hello ça marche !

Malheureusement on ne peut pas caller toute l'organisation du meetup un speaker en particulier ;). On a déjà des engagements niveau date avec les hosts (souvent un mois à l'avance).

Par rapport à notre planning, je te propose qu'on voit pour schedule ton sujet à la rentrée, car en juin on va faire une spécial React et on ne fait pas d'event sur Paris pendant l'été.

Bonne journée !

**Comment by Akheloes** [comment]
Je ne proposais pas de caller toute une orga sur mon schedule, seulement de me donner un heads-up suffisant pour pouvoir m'organiser. On en reparle à la rentrée, au pire ça sera pour une autre fois ou un autre sujet, no worries !

Belle journée

**Comment by paulsouche** [comment]
@Akheloes prochaine date le 10 septembre chez Takima. Dispo ?

**Comment by Akheloes** [comment]
@paulsouche : je ne suis plus à Paris désormais :(
Je close l'issue.

**Comment by Akheloes** [comment]
Pas possible d'organiser le talk.
