### ISSUE TITLE
Typescript, you and AI Search

### ISSUE THREAD

**Issue by malgamves** [ParisTypeScript/talks#47]
# Talk proposal - Paris TypeScript

## Talk description
* Title: Typescript, you and AI Search

Typescript is fun when it works well with other tools. My adventures have led me to discover it works well with applications that leverage AI.

We'll look at how Typescript features help us make the most out of AI Search and get into my journey building Generative Typescript Applications for the Web.

* Content (Briefly describe the content of the presentation):

* Duration:
  - [ ] Lightning (10 minutes)
  - [x] Regular (20 minutes)
  - [ ] Deep dive (40 minutes)
  > ⚠️ please specify in the description why you need a deep dive format to present your topic

* Level:
  - [x] Beginner
  - [ ] Intermediate
  - [ ] Advanced

## About you
* Name: Daniel 
* Twitter: @malgamves
* Company: Weaviate

**Comment by spontoreau** [comment]
Hello Daniel, thanks for your proposal !

Are you based in Paris ?

**Comment by malgamves** [comment]
Hey @spontoreau yes i am!

**Comment by spontoreau** [comment]
Ok great I keep you in touch

**Comment by malgamves** [comment]
thanks, looking forward to it!

**Comment by spontoreau** [comment]
Hello @malgamves how are you ?

We gonna organizing the next meetup May the 11th. Are you available ?

Thanks 😁

**Comment by malgamves** [comment]
Hey @spontoreau  May 11th is a Saturday, did you get the date right?

**Comment by spontoreau** [comment]
My bad, May 14th ^^'

**Comment by malgamves** [comment]
hey @spontoreau sadly i'll be out of town, do you have a june date? happy to do it in june

**Comment by spontoreau** [comment]
Ok no pb !

We will do an event in june, but dedicated to React. Next one will be in september for info

**Comment by spontoreau** [comment]
It's up to you ! it would be great, especially if you're available in June to do it :)

**Comment by malgamves** [comment]
Yup, June works! Do you have a date yet?

**Comment by spontoreau** [comment]
> Yup, June works! Do you have a date yet?

June the 11th probably

**Comment by malgamves** [comment]
Cool, that should be okay for me.

**Comment by spontoreau** [comment]
In the meantime we've found one last person for the lineup of the special react meetup, sorry... 😓

Maybe we can keep your initial topic for September and if you want to talk about React, I'll organize another meetup on that and we'll look for Speakers for June too : https://github.com/ReactParis/talks

**Comment by malgamves** [comment]
Hey @spontoreau great news, have a great event! Let's do September as I am out of town in June.

Regards,

**Comment by paulsouche** [comment]
@malgamves next event september 10th at Takima. Are you available ?

**Comment by malgamves** [comment]
Hey Paul,

Yes, it works for me thanks!
Anything else i should know?

*Daniel Madalitso Phiri*
malgamves.dev

**Comment by paulsouche** [comment]
Not for the moment. We will publish the event on [meetup](https://www.meetup.com/Paris-Typescript/) soon. I schedule your talk for next Meetup :pray:

**Comment by malgamves** [comment]
Great! I see it's up. 

Looking forward to it
