### ISSUE TITLE
Apprivoiser la guitare ET la programmation fonctionnelle !

### ISSUE THREAD

**Issue by basttran** [ParisTypeScript/talks#48]
# Proposition de talk - Paris TypeScript

## Description du talk
* Titre : Apprivoiser la guitare ET la programmation fonctionnelle !

* Contenu (Décrivez brièvement le contenu de la présentation) :

Je vous propose de m'accompagner dans l'appropriation de quelques motifs pertinents pour la programmation fonctionnelle avec TypeScript, autour de l'ébauche d'une appli d'aide à l'improvisation musicale. Nul besoin de revoir ses gammes ou de maîtriser l'API Web Audio avant de venir, il s'agira surtout d'adapter certaines fonctionnalités que j'ai pu coder 'naïvement' en première approche, en s'appuyant sur ces motifs.

Nous verrons par exemple comment représenter le branchement en série d'une guitare suivie d'éventuels effets et d'un ampli, comment gérer une recherche dans un dictionnaire d'accords qui serait incomplet, ou encore comment faire plus élégamment sonner des accords pour lesquels toutes les cordes ne sont pas jouées. Et ceci sans créer trop d'embranchements pour des cas de données absentes ou d'échecs de traitement !

Je vous promets de ne parler que très peu de monades, en revanche je ne vous garantis aucunement que nous éviterons d'en utiliser. Ce serait quand même dommage car j'en aurais préalablement implémenté une ou deux from scratch en Test Driven Development et j'aurai grand plaisir à vous les présenter et surtout à les convoquer pour surmonter les défis évoqués plus haut !

* Durée :
  - [ ] Lightning (10 minutes)
  - [X] Regular (20 minutes)
  - [ ] Deep dive (40 minutes)
  > ⚠️ Veuillez préciser dans la description pourquoi vous avez besoin de plus de temps pour présenter votre sujet. Pour information, les présentations longues ne sont pas prioritaires, car nous préférons avoir plusieurs présentations courtes pour les participants à l'événement.

* Niveau :
  - [X] Débutant
  - [ ] Intermédiaire
  - [ ] Avancé

## A propos de vous
* Nom et prénom : Tran Bastien
* Contact (X / LinkedIn / Autre) :
   - https://github.com/basttran
   - https://www.linkedin.com/in/basttran/
   - https://twitter.com/Hecatonchar
* Entreprise : Comet
* Rôle dans l'entreprise : Développeur

**Comment by spontoreau** [comment]
Hello Bastien,

Désolé je suis un peu en retard pour te répondre.

On a eu une autre proposition avant toi pour un talk sur la fp. J'aimerais bien répartir les deux sujets sur deux events différents, car ils ont probablement des intentions proches 😁

Histoire de m'aider à planifier, je vais déjà voir les disponibilités pour le prochain meetup, es ce que tu es dispo 14 mai ?

**Comment by spontoreau** [comment]
Hello Bastien comment ça va ?

Petite relance vu qu'on en a parlé à Devoxx ;)

**Comment by basttran** [comment]
Hello Sylvain :) 

Milles excuses, et je te confirme que je serai bien dispo le 14 mai (et au-delà) :)

**Comment by spontoreau** [comment]
Ok nickel, merci Bastien !

Je te rajoute dans le lineup :)
