### ISSUE TITLE
Migrer de Flow vers Typescript: la manière douce

### ISSUE THREAD

**Issue by AleBlondin** [ParisTypeScript/talks#5]
# Proposition de talk - Paris TypeScript

## Description du talk
* Titre : Migrer de Flow vers Typescript: la manière douce
* Contenu (Décrivez brièvement le contenu de la présentation) : La migration d’une techno à une autre donne des sueurs froides à la plupart des développeurs. C’est donc avec un peu d’appréhension que nous l’avons entrepris sur un de nos projets, un générateur d’applications React de quelques milliers de lignes. Celui-ci fonctionne avec les outils indispensables à tous développeurs web: linter, tests, babel, webpack, etc. ainsi que plusieurs fonctionnalités clés en main telle que de l'authentification via JWT.
Quelles sont les raisons qui nous ont amenés à changer d’outil de typage ? Comment avons nous surmonté les difficultés rencontrées, comme garder à tout moment une intégration continue fonctionnelle ? Et quel bilan pour cette migration ? Petit spoiler : on est hyper contents du résultat !

* Durée :
  - [ ] 10 minutes
  - [x] 20 minutes
  - [ ] 30 minutes
  - [ ] Autres, précisez:
* Niveau :
  - [x] Débutant
  - [x] Intermédiaire
  - [ ] Avancé

## A propos de vous

* Nom et prénom : Blondin Alexandre
* Twitter : https://twitter.com/AlexandreBlo
* Entreprise : Theodo

**Comment by AleBlondin** [comment]
Je suis preneur de feedbacks :) Que ce soit sur le titre, le contenu, etc.

**Comment by spontoreau** [comment]
Salut Alexandre et merci pour ta proposition!

C'est clairement un sujet qui va plaire, car les discussions autour de Flow & TypeScript sont nombreuses au meetup :)

Le contenu donne envie, j'ai hâte de voir ça ^^

**Comment by spontoreau** [comment]
Salut Alexandre, es ce que tu serais dispo le 3 juin pour faire ton talk?

On a du bousculer un peu le planning pour faire un event spécial le 23 avril, donc on va décaler le prochain meetup standard

**Comment by paulsouche** [comment]
Hello désolé mais erreur de notre part, on va faire ca le 4 juin... Toujours dispo ? Surtout peut on décaler le host ? Meri et encore désolé

**Comment by AleBlondin** [comment]
Hello ! Toujours ok pour le host et mon talk ! :smiley:
