### ISSUE TITLE
React Server Components, quèsaco?!

### ISSUE THREAD

**Issue by dubzzz** [ParisTypeScript/talks#50]
## Description du talk

* Titre : React Server Components, quèsaco?!

* Contenu (Décrivez brièvement le contenu de la présentation) :

Les React Server Components commencent à faire parler d'eux depuis quelques mois maintenant, mais que sont-ils vraiment ? À quoi tente t-il de répondre ?

Cette présentation vise à vous fournir les connaissances de bases autour de ce nouveau concept. L'objectif étant par la même occasion de clarifier ce qu'est React et ce que React n'est pas.

* Durée :
  - [ ] Lightning (10 minutes)
  - [x] Regular (20 minutes)
  - [ ] Deep dive (40 minutes)
  > ⚠️ Veuillez préciser dans la description pourquoi vous avez besoin de plus de temps pour présenter votre sujet. Pour information, les présentations longues ne sont pas prioritaires, car nous préférons avoir plusieurs présentations courtes pour les participants à l'événement.

* Niveau :
  - [x] Débutant
  - [ ] Intermédiaire
  - [ ] Avancé

## A propos de vous
* Nom et prénom : Nicolas Dubien
* Contact (X / LinkedIn / Autre) : dubzzz (on X)
* Entreprise : Pigment
* Rôle dans l'entreprise : Principal Software Engineer and Tech Lead

**Comment by spontoreau** [comment]
Hello @dubzzz je close cette proposition ?

**Comment by dubzzz** [comment]
Fait!

**Comment by spontoreau** [comment]
Thanks :pray:
