### ISSUE TITLE
Talk sur Vite

### ISSUE THREAD

**Issue by ArnaudBarre** [ParisTypeScript/talks#51]
# Proposition de talk - Paris TypeScript

## Description du talk

* Idée de titre : Vite, le bundler web simple et novateur

* Quelques point clés déjà en tête :
  - Expliquer l'approche "unbundled" de Vite en mode dev
  - Montrer le support built-in de TS
  - Expliquer la difference entre transpilation via esbuild et type checking via tsc
  - Montrer le système de plugin en écrivant un plugin pour supporter les imports yaml en quelques lignes

* Durée : Regular (20 minutes)

* Niveau : Intermédiaire

## A propos de vous

* Nom et prénom : Barré Arnaud
* Contact (X / LinkedIn / Autre) :
  - https://twitter.com/_ArnaudBarre
  - https://www.linkedin.com/in/arnaud-barre
* Entreprise : Carbometrix
* Rôle dans l'entreprise : Software engineer

**Comment by spontoreau** [comment]
Hello Arnaud, es ce que tu serais dispo le mardi 14 mai ?

Comme je te l'avais dit à React Paris, on est très intéressé pour passer en priorité ton sujet :)

**Comment by spontoreau** [comment]
Ok nickel !
