### ISSUE TITLE
Prompt engineering avec Typescript

### ISSUE THREAD

**Issue by dylantientcheu** [ParisTypeScript/talks#52]
# Proposition de talk - Paris TypeScript

## Description du talk
* Titre : Prompt engineering avec typescript

* Contenu (Décrivez brièvement le contenu de la présentation) :

Chez Algolia nous proposons un [Crawler](https://www.algolia.com/products/features/crawler/) très flexible. C'est cette technologie qui tourne derrière DocSearch

Nous avons un éditeur de configuration dans ce produit. Cet éditeur est une instance de Monaco qui permet de paramétrer votre crawler.

Nous avons utilisé TypeScript pour entraîner un AI Copilot sur tout ce qu'il faut savoir pour aider un utilisateur qui cherche à paramètrer son crawler.

Dans ce talk je parlerais de pourquoi, et comment TypeScript est le meilleur compagnon pour implémenter ceci.

* Durée :
  - [ ] Lightning (10 minutes)
  - [x] Regular (20 minutes)
  - [ ] Deep dive (40 minutes)
  > ⚠️ Veuillez préciser dans la description pourquoi vous avez besoin de plus de temps pour présenter votre sujet. Pour information, les présentations longues ne sont pas prioritaires, car nous préférons avoir plusieurs présentations courtes pour les participants à l'événement.

* Niveau :
  - [x] Débutant
  - [ ] Intermédiaire
  - [ ] Avancé

## A propos de vous
* Nom et prénom : Dylan Tientcheu
* Contact (X / LinkedIn / Autre) :
* Entreprise : Algolia 
* Rôle dans l'entreprise : Software Engineer

**Comment by spontoreau** [comment]
Merci Dylan pour ta proposition detalk !
