### ISSUE TITLE
Type-safe routing & navigation

### ISSUE THREAD

**Issue by e-krebs** [ParisTypeScript/talks#53]
# Talk proposal - Paris TypeScript

## Talk description
* Title: Type-safe routing & navigation

* Content (Briefly describe the content of the presentation):

Algolia offers a hosted AI Search solution for your data.
To manage your Algolia implementation, you have access to Algolia's [Dashboard](https://dashboard.algolia.com/dashboard) that has been existing for years.
In 2023 a new UI has been introduced specifically targeting less-technical users (merchandisers): Algolia [Merchandising Studio](https://dashboard.algolia.com/merchandising).
Building a new UI comes both with challenges & opportunities.
In this talk I will present how starting this new UI from scratch allowed us to build type-safe routing & navigation using some recursive Typescript along the way. Our use-case is based on top of `react-router-dom`, but should be applicable to other solutions.

* Duration:
  - [ ] Lightning (10 minutes)
  - [x] Regular (20 minutes)
  - [ ] Other
  > ⚠️ Please specify in the description why you need more time to present your topic. For your information, long presentations are not prioritized first, as we prefer to have several short presentations for people attending the event.

* Level:
  - [ ] Beginner
  - [x] Intermediate
  - [ ] Advanced

## About you
* Name: Emmanuel Krebs
* Contact (X/LinkedIn/Other): [@emmkrebs](https://twitter.com/emmkrebs)
* Company: Algolia
* Role in the company: Senior Software Engineer

**Comment by spontoreau** [comment]
Hello Emmanuel, merci pour ta proposition !

Es ce que tu serais dispo le 11 juin ? On va faire un event spécial React et ton talk serait parfait pour compléter le line up 😁

**Comment by e-krebs** [comment]
> Hello Emmanuel, merci pour ta proposition !
> 
> Es ce que tu serais dispo le 11 juin ? On va faire un event spécial React et ton talk serait parfait pour compléter le line up 😁

à priori je suis dispo & je le note dans mon agenda!
(mon équipe sera de passage à Paris cette semaine là & je ne connais pas encore le planning donc disons que je suis confirme à 75% pour l'instant)

**Comment by spontoreau** [comment]
Ok super !

Tiens moi au courant ;)

**Comment by e-krebs** [comment]
@spontoreau j'en ai discuté et c'est bon de mon côté.
Certains de mes collègues (anglophones) viendront peut-être!
Tu sais déjà où ce sera hébergé ?

**Comment by spontoreau** [comment]
Hello @e-krebs ok merci pour la confirmation !

J'ai une sync avec le host potentiel début de semaine prochaine. Ça sera dans Paris 3e normalement, je te tiens au courant ;)

**Comment by e-krebs** [comment]
je serais probablement là le 14 mai au fait 🙂

**Comment by spontoreau** [comment]
> je serais probablement là le 14 mai au fait 🙂

Ok super 😄
