### ISSUE TITLE
3 TS configs pour un starter Vite, vraiment ?

### ISSUE THREAD

**Issue by ArnaudBarre** [ParisTypeScript/talks#59]
# Proposition de talk - Paris TypeScript

## Description du talk

* Titre : 3 TS configs pour un starter Vite, vraiment ?

* Contenu (Décrivez brièvement le contenu de la présentation) : Depuis quelques mois les starters Vite pour React/Vue/Solid contiennent 3 fichiers tsconfig ! Je vous expliquent les subtilités des "project references" pour bien gérer le typing de code web & node au sein d'un même projet.
 
* Durée :
  - [x] Lightning (10 minutes)
  - [ ] Regular (20 minutes)
  - [ ] Deep dive (40 minutes)

* Niveau :
  - [ ] Débutant
  - [x] Intermédiaire
  - [ ] Avancé

## A propos de vous

* Nom et prénom : Barré Arnaud
* Contact (X / LinkedIn / Autre) : https://x.com/_ArnaudBarre / https://www.linkedin.com/in/arnaud-barre/
* Entreprise : Carbometrix
* Rôle dans l'entreprise : Software engineer

**Comment by spontoreau** [comment]
Hello Arnaud, merci pour ta proposition.

Je reviens vers toi rapidement !

**Comment by laurentpayot** [comment]
Est-ce que le talk prend en compte le mic-mac concernant la détection des `tsconfig.json` ?(présent dans TS 5.6 beta, viré de 5.6 RC, peut-être remis dans 5.7): https://devblogs.microsoft.com/typescript/announcing-typescript-5-6-rc/#whats-new-since-the-beta

**Comment by ArnaudBarre** [comment]
Ce n'est pas prévu de parler de ça explicitement, le but de ce talk c'est plutôt de recommander l'approche que ce changement cherche à éviter (i.e. un seul tsconfig.json) ce qui permet de fixer aujourd'hui les problèmes de mauvais context d'éditeur pour certains fichiers

**Comment by spontoreau** [comment]
Salut Arnaud,

Tu serais dispo pour le prochain meetup le 12 novembre ?

**Comment by ArnaudBarre** [comment]
Salut Sylvain, oui je suis dispo je l'avais déjà dans l'agenda !

**Comment by spontoreau** [comment]
Ok parfait !

Merci Arnaud :pray:
