### ISSUE TITLE
Talk proposal: Type Aware Assertion functions and Type Level testing. 

### ISSUE THREAD

**Issue by garronej** [ParisTypeScript/talks#60]
# Talk proposal - Paris TypeScript

## Talk description
* Title: Type Aware Assertion Functions and Type-Level Testing

* Content (Briefly describe the content of the presentation):  

Type-level assertions, enabled by [the `asserts` keyword](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#assertion-functions), have been a part of TypeScript for over five years, yet they aren't widely adopted.  
In this talk, I'll try to make a case for the value of this feature and show how it can be easily leveraged.

* Duration:
  - [ ] Lightning (10 minutes)
  - [x] Regular (20 minutes)
  - [ ] Other
  > ⚠️ Please specify in the description why you need more time to present your topic. For your information, long presentations are not prioritized first, as we prefer to have several short presentations for people attending the event.  
  
* Level:
  - [ ] Beginner
  - [ ] Intermediate
  - [ ] Advanced  
  
Not applicable. The approaches I'll share can be leveraged by beginners, but they are often not common knowledge even for advanced TypeScript developers.

## About you
* Name: Joseph Garrone
* Contact (X/LinkedIn/Other): https://github.com/garronej
* Company: Insee
* Role in the company: Tech Lead

**Comment by spontoreau** [comment]
Salut Joseph, comment vas-tu ?

Trés bon sujet, je pense que ça va intéresser du monde. Est ce que tu serais dispo le 12 novembre pour le prochain meetup ?

**Comment by garronej** [comment]
Top! Merci!

**Comment by spontoreau** [comment]
Salut Joseph, est ce que tu serais dispo le 12 novembre pour faire ton sujet ?

**Comment by garronej** [comment]
Salut Sylvain, oui!

**Comment by spontoreau** [comment]
Nickel, je te rajoute dans le lineup !
