### ISSUE TITLE
Talk proposal: Hooks-o-mania: How We Got Hooked and Why We're Breaking Free

### ISSUE THREAD

**Issue by emmagoldblum** [ParisTypeScript/talks#63]
# Proposition de talk - Paris TypeScript

## Description du talk
* Titre : Hooks-o-mania: How We Got Hooked and Why We're Breaking Free

* Contenu (Décrivez brièvement le contenu de la présentation) :
Picture this: It's 2019, and hooks burst onto the global scene. They promised to revolutionize how we tinker with React component lifecycles - so simple, so elegant! We went hook-crazy, sprinkling them like confetti at a developer's wedding.
Fast forward, and our app turned into a glitchy disco ball of bugs and performance issues. Oops! Now we're on a grand "de-hooking" adventure, swapping out unnecessary hooks for observables like we're trading Pokémon cards. Join us for a  retrospective of our hook-filled journey - from hook-euphoria to hook-hangover!

* Durée :
  - [x] Lightning (10 minutes)
  - [ ] Regular (20 minutes)
  - [ ] Deep dive (40 minutes)
  > ⚠️ Veuillez préciser dans la description pourquoi vous avez besoin de plus de temps pour présenter votre sujet. Pour information, les présentations longues ne sont pas prioritaires, car nous préférons avoir plusieurs présentations courtes pour les participants à l'événement.

* Niveau :
  - [ ] Débutant
  - [x] Intermédiaire
  - [ ] Avancé

## A propos de vous
* Nom et prénom : Goldblum Emma
* Contact (X / LinkedIn / Autre) : https://www.linkedin.com/in/emma-goldblum/
* Entreprise : Alan
* Rôle dans l'entreprise : Software Engineer

**Comment by spontoreau** [comment]
Salut Emma,

Merci pour ton talk, je vais pouvoir compléter le lineup sur meetup :)
