### ISSUE TITLE
gRPC avec Typescript

### ISSUE THREAD

**Issue by ByJC** [ParisTypeScript/talks#7]
> # Proposition de talk - Paris TypeScript
> ## Description du talk
> * Titre : "gRPC avec Typescript" ou
>   "Qu'est ce que le gRPC et comment l'utiliser avec TS"
> * Contenu (Décrivez brièvement le contenu de la présentation) :
>   Vous faites de la communication entre microservices en REST mais rencontrez des problèmes de performances.
>   Vous voulez avoir un "contrat" avec vos API.
>   Sur cette presentation, nous allons présenter et explorer le gRPC, un framework permettant de faire de la communication entre un client et un server basé sur le RPC et les protocol buffers.
>  
> * Durée :
>   
>   * [ ]  10 minutes
>   * [ ]  20 minutes
>   * [ ]  30 minutes
>   * [x]  Autres, précisez: 25 min
> * Niveau :
>   
>   * [x]  Débutant
>   * [x]  Intermédiaire
>   * [ ]  Avancé
> 
> ## A propos de vous
> * Nom et prénom : Jean-Charles FAUVIN
> * Twitter : [@**ByJCf**](https://twitter.com/ByJCf)
> * Entreprise : Tradelab

**Comment by spontoreau** [comment]
Bonjour Jean-Charles, merci pour ta proposition de talk 👍

**Comment by spontoreau** [comment]
Thank you @ByJC !
