### ISSUE TITLE
Présentation de Tumau, un framework HTTP écrit avec et pour TypeScript

### ISSUE THREAD

**Issue by etienne-dldc** [ParisTypeScript/talks#9]
# Proposition de talk - Paris TypeScript

## Description du talk
* Titre : 
Présentation de Tumau, un framework HTTP écrit avec et pour TypeScript

* Contenu (Décrivez brièvement le contenu de la présentation) :
Présentation de [Tumau](https://github.com/etienne-dldc/tumau), un framework similaire à Express ou Koa mais écrit avec et pour TypeScript.

Au programme:
- HTTP, quelques rappels
- Les middleware, comment ca marche ?
- Typer le Context ?
- Le Routing et le matching d'url avec [Chemin](https://github.com/etienne-dldc/chemin)

* Durée :
  - [ ] 5 minutes (Lightning talk)
  - [ ] 10 minutes
  - [ ] 20 minutes
  - [x] 30 minutes
  - [ ] Autres, précisez:
* Niveau :
  - [ ] Débutant
  - [x] Intermédiaire
  - [ ] Avancé

## A propos de vous
* Nom et prénom : Étienne DELADONCHAMPS
* Twitter : @Etienne_dot_js
* Entreprise :

**Comment by spontoreau** [comment]
Update avec le template, merci pour la proposition Etienne!
